### ISSUE TITLE
Cannot start server due to incorrect dependency specification in Flask

### ISSUE THREAD

**Issue by Pfanfel** [dfaranha/au-syssec-f24-assignments#1]
I tried to get the server running using the recommended setup from the readme and got the following error:

```
Traceback (most recent call last):
  File "/home/michi/repos/au-syssec-f24-assignments/crypto/cbc-padding-oracle/.venv/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/home/michi/repos/au-syssec-f24-assignments/crypto/cbc-padding-oracle/.venv/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/michi/repos/au-syssec-f24-assignments/crypto/cbc-padding-oracle/.venv/lib/python3.10/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/michi/repos/au-syssec-f24-assignments/crypto/cbc-padding-oracle/.venv/lib/python3.10/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/michi/repos/au-syssec-f24-assignments/crypto/cbc-padding-oracle/.venv/lib/python3.10/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/michi/repos/au-syssec-f24-assignments/crypto/cbc-padding-oracle/.venv/lib/python3.10/site-packages/werkzeug/urls.py)
```
To get it working locally, I used [this](https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr) solution.

My requirments.txt looks like this:
```
flask==2.2.2
Werkzeug==2.3.7
pycryptodome==3.10.1
```

**Comment by dfaranha** [comment]
Thanks! I updated the `requirements.txt` with the suggested deps in both tasks.
